.TH "keyboard_listener/keyboard_listener.cpp" 3 "Wed May 20 2020" "EngineeringProject2020" \" -*- nroff -*-
.ad l
.nh
.SH NAME
keyboard_listener/keyboard_listener.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <SoftwareSerial\&.h>\fP
.br
\fC#include <PS2Keyboard\&.h>\fP
.br
\fC#include <Keypad\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBROWS\fP   4"
.br
.RI "Number of rows in keypad\&. "
.ti -1c
.RI "#define \fBCOLS\fP   5"
.br
.RI "Number of columns in keypad\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "SoftwareSerial \fBbs\fP (50, 4)"
.br
.RI "Create instance of SoftwareSerial class, RX on pin 50 (unused), TX on 4 pin\&. "
.ti -1c
.RI "void \fBsetup\fP ()"
.br
.ti -1c
.RI "void \fBloop\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "char \fBkeys\fP [\fBROWS\fP][\fBCOLS\fP]"
.br
.RI "Keypad layout\&. "
.ti -1c
.RI "byte \fBrowPins\fP [\fBROWS\fP] = {A0, A1, A2, A3}"
.br
.RI "Pin map for rows for keypad\&. "
.ti -1c
.RI "byte \fBcolPins\fP [\fBCOLS\fP] = {12, 11, 10, 9, 8}"
.br
.RI "Pin map for columns for keypad\&. "
.ti -1c
.RI "Keypad \fBkeypad\fP = Keypad( makeKeymap(\fBkeys\fP), \fBrowPins\fP, \fBcolPins\fP, \fBROWS\fP, \fBCOLS\fP)"
.br
.RI "Create keypad instance\&. "
.ti -1c
.RI "PS2Keyboard \fBkeyboard\fP"
.br
.RI "Create instance of PS2Keyboard class\&. "
.ti -1c
.RI "int \fBcn\fP = 0"
.br
.RI "Counter for ':'\&. "
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define COLS   5"

.PP
Number of columns in keypad\&. 
.PP
Definition at line 8 of file keyboard_listener\&.cpp\&.
.SS "#define ROWS   4"

.PP
Number of rows in keypad\&. 
.PP
Definition at line 6 of file keyboard_listener\&.cpp\&.
.SH "Function Documentation"
.PP 
.SS "SoftwareSerial bs (50, 4)"

.PP
Create instance of SoftwareSerial class, RX on pin 50 (unused), TX on 4 pin\&. 
.SS "void loop ()"
Check if scanner is available
.PP
get character from scanner
.PP
get key from Keypad
.PP
wait some time
.PP
Definition at line 38 of file keyboard_listener\&.cpp\&.
.SS "void setup ()"
start SoftwareSerial for keyboard
.PP
start Serial for barcode scanner
.PP
start PS2keyboard for barcode scanner
.PP
Definition at line 28 of file keyboard_listener\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "int cn = 0"

.PP
Counter for ':'\&. 
.PP
Definition at line 37 of file keyboard_listener\&.cpp\&.
.SS "byte colPins[\fBCOLS\fP] = {12, 11, 10, 9, 8}"

.PP
Pin map for columns for keypad\&. 
.PP
Definition at line 18 of file keyboard_listener\&.cpp\&.
.SS "PS2Keyboard keyboard"

.PP
Create instance of PS2Keyboard class\&. 
.PP
Definition at line 26 of file keyboard_listener\&.cpp\&.
.SS "Keypad keypad = Keypad( makeKeymap(\fBkeys\fP), \fBrowPins\fP, \fBcolPins\fP, \fBROWS\fP, \fBCOLS\fP)"

.PP
Create keypad instance\&. 
.PP
Definition at line 21 of file keyboard_listener\&.cpp\&.
.SS "char keys[\fBROWS\fP][\fBCOLS\fP]"
\fBInitial value:\fP
.PP
.nf
= {
  {'7', '8', '9', '&', 'C'},
  {'4', '5', '6', 'X', '^'},
  {'1', '2', '3', 'F', 'v'},
  {'0', '\&.', 'Q', 'O', '/'}
}
.fi
.PP
Keypad layout\&. 
.PP
Definition at line 9 of file keyboard_listener\&.cpp\&.
.SS "byte rowPins[\fBROWS\fP] = {A0, A1, A2, A3}"

.PP
Pin map for rows for keypad\&. 
.PP
Definition at line 16 of file keyboard_listener\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for EngineeringProject2020 from the source code\&.
